version: "3"
services:

  database:
    image: postgres:12.3
    container_name: ygo_server_database
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"

  app:
    image: ygo_server
    container_name: ygo_server
    depends_on:
    - database
    ports:
    - 8000:8000
    environment:
      ADMIN_KEY: "${ADMIN_KEY-admin}"

volumes:
  database_data:
